### ISSUE TITLE
Make Darkspore launch

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/Darkspore-LS#1]
By using Davo instructions:
http://www.davoonline.com/phpBB3/viewtopic.php?f=88&t=6386

Using the SporeModder or the SporeMaster:
https://github.com/Emd4600/SporeModder
https://code.google.com/archive/p/sporemaster/downloads

We are capable of pressing the Launch button. Still, the game does give the following error on launch:

<img width="434" alt="screen shot 2018-11-17 at 13 50 00" src="https://user-images.githubusercontent.com/8976483/48662886-b7c1c900-ea6f-11e8-9f9c-9f120f3b032a.png">

According to Flask, the only request made up to this point is `api.config.getConfigs`, so we need to find out what does `getConfigs` needs to respond in order to avoid that warning.

**Comment by vitor251093** [comment]
Known details include a sample of the said GET request:
**include_patches:** 'true'
**version:** '1'
**include_settings:** 'true'
**method:** 'api.config.getConfigs'
**build:** '5.3.0.103'

Those parameters are already retrieved by Python in the code, so they can be used to make specific responses, if needed.

**Comment by vitor251093** [comment]
Also, regarding the main EXE for Darkspore, it seems to have been compiled with Microsoft Visual C++ 6.0 or Visual Studio 2005.

**Comment by vitor251093** [comment]
`api.config.getConfigs` is also called by the `Client` object/class in the package files. May be easier to analyse.

**Comment by vitor251093** [comment]
Maybe the `Client` object can be analysed with a modified version of EA's Webkit.
https://gpl.ea.com/darkspore.html

EA used OWB to create it, and its source can be found here:
http://fabportnawak.free.fr/owb/src/

**Comment by vitor251093** [comment]
Hello @bhelyer ,

> The client may well be waiting for the server to send a request to it -- and when that times out, you get the error, without your emulated server telling you it's dropping a request. So handing the config requests correctly (which as you've discovered, with no information about the responses, is difficult enough) may not be enough.

While that would be a possibility, in order to do that the game cliente would need to leave an open door so it could listen to the server; basically reserving a port in the computer. It's possible to detect when a port is reserved, so it would be an extra step, but not an impossible one ;)

> Even if you were to get the game running, the challenges will only increase. While it's possible that the game runs client side, and simply is listening for a heartbeat or similar from the game server, I would assume that the server contains the actual game logic (aside from being the obvious architecture once management decided the game is always online, people complaining about lag is probably the biggest clue on that front). If the game server does contain the game logic, reverse engineering the communication protocol without access to the server, and then having to glean game behaviour from let's play videos would be a simply colossal task, requiring a lot of people and a lot of time.

Yup, I'm aware of that. Unfortunately that means that the private server will hardly be exactly like the original game, but that's one of the reasons for making Darkspore LS open-source: the server side will be fully configurable, so it will be just a matter of time until someone manages to configure it properly to mimic the original game in a very close way. Again: it will hardly be equal to the original game, but if it gets close, it will still be fine.

> I wish you all the best (really! I never played Darkspore, and I am curious about it. A game vanishing from history like some kind of lost silent film is really sad) and I hope I am wrong about the scale of work required.

You are surely not wrong about the difficulties, and surely not wrong about the scale of work as well, since reverse engineering and brute force are some of the slowest methods for achieving what we want. However, I guess this is what makes this project so interesting for me... I guess I like the challenge :D 

Thanks for your supporting words :) Also, keep in touch. Who knows when we gonna have a functional server? Once that happen, the real tests will start ;)

**Comment by nonchip** [comment]
sooo I bought the game a few years ago after the servers were already offline (because the retailer just didn't care about the product recall), I got experience in programming and network stuff, not so much in windows disassembly though, so if there's anything i could help with i'd be glad :3

**Comment by vitor251093** [comment]
Hello @nonchip !
Well, there is one thing: the EAWebKit.dll is open source. It can be found here:
https://gpl.ea.com/darkspore.html

By using Visual Studio 2008, it's possible to rebuild it in Debug mode, which I know it has by analysing the source, but I still couldn't find time to build it. During the game development, the Debug mode was most probably used to test the game, so some features are most likely locked behind it, like the ability to list the properties of an object, or gathering a function code as a string.

If my theory is correct, that dll may be the key to find out what the Darkspore launcher it does with the getConfigs output, and so discover a proper way to mock its response.

**Comment by nonchip** [comment]
if the launcher uses webkit to access the api (which would be pretty ugly design), yes. i suspect it's mostly used to render a "news" section in the launcher like pretty much any other game launcher that uses webkit and/or an IE frame.

**Comment by vitor251093** [comment]
After your comment, I've analysed the `Client` object more deeply. Unfortunately it debunked my last theory, but it brought progress.

> if the launcher uses webkit to access the api (which would be pretty ugly design), yes. i suspect it's mostly used to render a "news" section in the launcher like pretty much any other game launcher that uses webkit and/or an IE frame.
Well, it does not use the launcher to access the API most of the time. There are two different cases in the `Web.package` source:

Sample 1: Creating a new script object to access the API directly
```
         var child = document.getElementById("Server_fetch");
         if (child != null)
         {
            parent.removeChild(child);
         }
         child = document.createElement("script");
         child.id = 'Server_fetch';
         child.type= 'text/javascript';
         child.onload = function() {serverstatusdataload = true;
         };
         child.onerror = function() { serverstatusdataload = false; setStickyMessage(localizedstringmap['LOSTCONNECTION']);
          var container = document.getElementById("Server_condition");
          var innervar = '<div style="color:#FFFFFF;font-family:Arial;font-size:11px;" align="right">'+localizedstringmap['FAILEDTOCONNECT'];
          innervar += '<img src="images/icon_light_red.png" style="position: relative;top: 3px; left: 2px;"  /></div>';
          container.innerHTML = innervar;
          };
         var d=new Date();
         child.src= 'http://config.darkspore.com/api?version=1&method=api.status.getStatus&format=json&callback=updateServerStatus(data)'+'#'+d.getTime();
         parent.appendChild(child);
```

Sample 2: Using the Client variable to access it using the game
```
parent.Client.callSporeNet("api.creature.getCreature","id="+creatureid+"&include_parts=true"+"&include_abilities=true","spgetcreaturecallback");
```

I've used the _left progress comment_ area in the launcher has my debugging tool at this point. It seems that if I try to print `Client.callSporeNet`, I get something like that (can't see the difference between the special characters properly in the Darkspore font):

```
function callSporeNet() { [native code] }
```

Based on that, and in the fact that `Client.playCurrentApp` is also a thing (the function that closes the launcher and makes the game start), I guess we can safely assume that `Client` is been used to communicate with the game itself, and that each one of its functions are, in fact, `Function`s.

> have you checked the `web.package` for any mention of that api call? if not i'd say it's probably safe to assume the webkit stuff is used for the launcher UI (it is a html renderer after all, not a network library) while the game directly calls the api.
Not that one, unfortunately. It seems to only make a directly API call for getStatus.

> i'd rather advise trying to follow the data around the exe in a debugger and/or decompiling it if it's IL.
maybe just open it in IDA, r2 or similar, look for the string, the function call referencing it and then see what it does to the result?
I've also tried that some time ago, although I'm not experienced with those tools and couldn't take much info out of them. However, there is something that I can safely assume from those times: the Darkspore EXE does contain the getConfigs method string (`api.config.getConfigs`), like I mentioned in one of my prior comments:

> The `api.config.getConfigs` string can be found at `00fd8644` by using Borg Disassembler.

Which supports your theory that the API calls are made by the app itself. In that case, a debugging tool is surely the way to go. Do you have any experience with debugging/decompilation?

Another thing (most probably important only to the future), is that now I know all the Client functions:
- retrieveAbilityPngKey
- getWebHost
- getSnApiHost
- getLocaleId
- getPlayerOnlineId
- retrieveAttributeString
- retrieveLocaleString
- unfollowPlayer
- registrationEmail
- setSelectedFriend
- setGameOption
- sendTellToPlayer
- inviteToGroup
- followPlayer
- getLobbyMembersAsJSON
- editCreature
- closeSurveyWindow
- closeBRSWindow
- closeWindow
- callSporeNet

**Comment by nonchip** [comment]
> Sample 1: Creating a new script object to access the API directly

the way it essentially just does a `document.write("<script src='api'>")` there together with the arguments to that api call strongly suggest JSONp (json with padding, aka a javascript snippet calling a callback function with the json as its typeof(object) argument).

the callback "updateServerStatus" (do we have the source code for that maybe? seems to just be a global js function, and is probably gonna hint at (some of) the content to expect from the json) sounds like it's just checking if the server is available to decide whether or not the play button shows up and maybe something like "X players currently online".

> Sample 2: Using the Client variable to access it using the game

this failing is probably what's currently preventing the game from running. i doubt you'd be able to debug any of those functions using the webkit library, since they seem to all be native (= C/C++/.Net/whatever) code just exposed to js in the client object.

so essentially since both the binary game blob and the js access at least `getConfig` we could maybe figure out some info as to what that specific call returns by looking at the js but i'm afraid we probably have to dig through the binary (by finding all the api calls and check their surroundings for what they do to the data supplied to/returned from them) for most of the other calls.

> In that case, a debugging tool is surely the way to go. Do you have any experience with debugging/decompilation?

well, in theory, but not a lot of practical experience i'm afraid. i've debugged my own stuff obviously, but since they don't include debugger-friendly information (=non-stripped binaries and sources), i'm afraid the only thing we could do is:

* hope they used a .NET IL compiler so it's decompileable
* if they didn't, sift through the binary with tools like IDA or radare2, the latter of which i've used (the former appears nicer to use but is horribly expensive) but not to this extend and not on exe files (mostly ELFs and Z80 binaries).

also i don't have windows, so i'd be stuck with running it through wine and using mostly linux compatible tools (r2 is, but as i said, not a lot of experience here sadly).

**Comment by vitor251093** [comment]
I just used x64dbg and I bring good news. I'm following the path of `call`s, and at this point, it seems that the getConfigs is indeed still made with EAWebKit; it's used directly by the game instead of the launcher, but it seems to use the dll to make the request. Not 100% sure, but it seems very likely.

**Comment by vitor251093** [comment]
> the callback "updateServerStatus" (do we have the source code for that maybe? seems to just be a global js function, and is probably gonna hint at (some of) the content to expect from the json) sounds like it's just checking if the server is available to decide whether or not the play button shows up and maybe something like "X players currently online".

That's right. It's inside Web.package. D-LS already mocks that one ;)

**Comment by vitor251093** [comment]
> hope they used a .NET IL compiler so it's decompileable
As far as I know, they used Visual Studio 2005 or Visual Studio 2008.

**Comment by nonchip** [comment]
> Maybe I just don't know which is the proper callback.

well depends on if it even uses jsonp for that one (= if it injects the result as javascript or just decodes the json or even uses a completely different format), but if it does, it should say so in the request arguments.

> As far as I know, they used Visual Studio 2005 or Visual Studio 2008.

haven't used either of them but afaik those are IDEs, not language implementations. what i'm hinting at is: if it produced a .NET binary, it can likely be decompiled from the intermediate language representation, while a "normal" exe is just plain opcodes you have to disassemble which is more of a pain to analyze afterwards (i'm just gonna assume your intel binary isn't that perfectly fluent in text and speech :stuck_out_tongue: ).

**Comment by vitor251093** [comment]
> haven't used either of them but afaik those are IDEs, not language implementations. what i'm hinting at is: if it produced a .NET binary, it can likely be decompiled from the intermediate language representation, while a "normal" exe is just plain opcodes you have to disassemble which is more of a pain to analyze afterwards (i'm just gonna assume your intel binary knowledge isn't that perfectly fluent because nobody's is 😛 ).

I know. I mentioned that it was made with VS2005/2008 because, as far as I know, it primally targets the .NET framework.
https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#.NET_(2002)

**Comment by vitor251093** [comment]
Although, I can run it in Wine without Mono or any .NET winetrick, so it's unlikely that it uses .NET; the same applies to SPORE, which as far as I know, use the "same" engine (it was modified for Darkspore).

**Comment by nonchip** [comment]
yeah doesn't seem to be .net sadly (well that's a sentence i never thought i'd say :stuck_out_tongue_closed_eyes: ), so i guess we'd be stuck with disassembling the binary :/

**Comment by nakti** [comment]
I've compiled this using 2017 studio with 2008 compiler, and managed to debug. But I didn't pay much effort to it, so I didn't find any place that makes the request. I also cannot launch docker on my computer, it makes Windows crash on startup)

**Comment by vitor251093** [comment]
> yeah doesn't seem to be .net sadly (well that's a sentence i never thought i'd say 😝 ), so i guess we'd be stuck with disassembling the binary :/

lol true story xD

> I've compiled this using 2017 studio with 2008 compiler, and managed to debug. But I didn't pay much effort to it, so I didn't find any place that makes the request. I also cannot launch docker on my computer, it makes Windows crash on startup)

I haven't tried, but technically, you should be able to launch it directly in Windows if you follow that guide:
http://timmyreilly.azurewebsites.net/python-flask-windows-development-environment-setup/

And then launch main.py (inside the darkspore_server folder) directly with Python like this (at least this is how he/she does in the last print):
```
python main.py
```

That's exactly why I made it in Docker; it's much easier and faster to prepare to environment; although I didn't know it was unstable in Windows.

**Comment by vitor251093** [comment]
> But I didn't pay much effort to it, so I didn't find any place that makes the request.

I'm not sure if we ever will... based in that:

> I guess we can safely assume that `Client` is been used to communicate with the game itself, and that each one of its functions are, in fact, `Function`s.

A `Function` (with an upper 'F') in JS standards is a native code, which means that it can only be called; differently from regular JS functions, which can even be turned into strings (which was the main desire in building the dll for Debug, unfortunately...); and I mean the function itself, not its returned value.

Although, it may still be useful to detect which are the functions in the Client object and the ones available in the JS; while most likely getConfigs is directly requested by the game and does not interact with the WebKit, the more we learn about the Client structure, the best; it will surely be used in the future.

**Comment by nonchip** [comment]
if i had to guess i'd say they're probably all `Function`s, because likely the whole Client js object is just a binding to whatever object type it is in the native implementation. at least that's what i would do, just easier to give webkit a whole object instead of patching a bunch of native functions into an existing one that's mixed with js stuff.

**Comment by vitor251093** [comment]
> if i had to guess i'd say they're probably all `Function`s, because likely the whole Client js object is just a binding to whatever object type it is in the native implementation. at least that's what i would do, just easier to give webkit a whole object instead of patching a bunch of native functions into an existing one that's mixed with js stuff.

Makes sense.

> a thing we really could use is a network sniff of the running game, but a quick google search seems to result in pretty much nothing :/ so i guess either time machine or binary disassembly and a lot of pain (the unpleasant kind) :/

I've looked for that a bunch of times already; still couldn't find anyone with pcap's of Darkspore.

> dunno how much time i can muster for this (lots of real life stress) currently so might take a while until i have any results 

Sure, take your time ;) 

> but i'm gonna try a few different disassemblers/debuggers and see what i can find.

Thanks! :D

**Comment by vitor251093** [comment]
Thanks to @nonchip and @haradons (Discord) I could find out the proper parameters to launch the game. That issue was finally solved.
